### ISSUE TITLE
Compatibility with non/algebra

### ISSUE THREAD

**Issue by denisrosset** [mpilquist/fundamentum#3]
Hi @mpilquist,

there is already a project underway to create algebraic structures in common between algebird and spire. There is overlap with Structures in the Semigroup/Monoid departement.

Just wanted you to know.

**Comment by mpilquist** [comment]
Hi Denis,

Thanks for mentioning algebra. I'm working closely with @non and @tixxit, amongst others -- @non has a very similar project underway, http://github.com/non/cats, which builds on algebra. The biggest difference between this project and cats is that it is guaranteed to have zero dependencies and a very, very slow release cycle. My goal is to never break binary compatibility in a given Scala 2.x release.

I'll add some info to the README, and specifically the FAQ, that discusses this topic.

Thanks!
