### ISSUE TITLE
Add scala.js support

### ISSUE THREAD

**Issue by mpilquist** [mpilquist/fundamentum#6]
Not sure exactly what's involved in doing this. Ideally, new releases of scala.js should not require re-releasing Structures. If the tooling allows for that, let's configure this project for scala.js publishing. If not, then let's create a companion project that builds Structures for scala.js.

**Comment by mpilquist** [comment]
@matthughes Do you want to look in to this? :)

**Comment by mpilquist** [comment]
Note - if we need to move away from Discipline and replace with something smaller or built directly in to the laws project, that's fine with me.

**Comment by matthughes** [comment]
I'll take a look.  Not sure what the plan is post 1.0, but everything up till then requires new release.  _However_, the way the artifact is versioned, it wouldn't be a new version of Strucutres; it would be treated just as if you were cross compiling it against different Scala versions.

**Comment by matthughes** [comment]
So as of 0.6.0 (http://scala-lang.org/news/2015/02/05/scala-js-no-longer-experimental.html):

> The standard library of Scala.js (the scala.scalajs.js package) will remain backward source and binary compatible.

So I don't think we necessarily need a separate project.
